// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2023-2024, Advanced Micro Devices, Inc.
 */

#include "npu_common.h"

/* Address definition from Phoenix Ryzen 7040 docs */
#define MPNPU_PUB_SEC_INTR		0x3010090
#define MPNPU_PUB_PWRMGMT_INTR		0x3010094
#define MPNPU_PUB_SCRATCH2		0x30100A0
#define MPNPU_PUB_SCRATCH3		0x30100A4
#define MPNPU_PUB_SCRATCH4		0x30100A8
#define MPNPU_PUB_SCRATCH5		0x30100AC
#define MPNPU_PUB_SCRATCH6		0x30100B0
#define MPNPU_PUB_SCRATCH7		0x30100B4
#define MPNPU_PUB_SCRATCH9		0x30100BC

#define MPNPU_SRAM_X2I_MAILBOX_0	0x30A0000
#define MPNPU_SRAM_X2I_MAILBOX_1	0x30A2000
#define MPNPU_SRAM_I2X_MAILBOX_15	0x30BF000
/* End Phoenix Ryzen 7040 macros */

#define MPNPU_APERTURE0_BASE		0x3000000
#define MPNPU_APERTURE1_BASE		0x3080000
#define MPNPU_APERTURE2_BASE		0x30C0000

/* <device name>_<bar>_<enum name>_ADDR, see enum psp_reg_idx */
#define PHX_PSP_PSP_CMD_REG_ADDR	MPNPU_PUB_SCRATCH2
#define PHX_PSP_PSP_ARG0_REG_ADDR	MPNPU_PUB_SCRATCH3
#define PHX_PSP_PSP_ARG1_REG_ADDR	MPNPU_PUB_SCRATCH4
#define PHX_PSP_PSP_ARG2_REG_ADDR	MPNPU_PUB_SCRATCH9
#define PHX_PSP_PSP_INTR_REG_ADDR	MPNPU_PUB_SEC_INTR
#define PHX_PSP_PSP_STATUS_REG_ADDR	MPNPU_PUB_SCRATCH2
#define PHX_PSP_PSP_RESP_REG_ADDR	MPNPU_PUB_SCRATCH3
/* <device name>_<bar>_<enum name>_ADDR, see enum npu_smu_reg_idx */
#define PHX_SMU_SMU_CMD_REG_ADDR	MPNPU_PUB_SCRATCH5
#define PHX_SMU_SMU_ARG_REG_ADDR	MPNPU_PUB_SCRATCH7
#define PHX_SMU_SMU_INTR_REG_ADDR	MPNPU_PUB_PWRMGMT_INTR
#define PHX_SMU_SMU_RESP_REG_ADDR	MPNPU_PUB_SCRATCH6
#define PHX_SMU_SMU_OUT_REG_ADDR	MPNPU_PUB_SCRATCH7
/* <device name>_<bar>_<enum name>_ADDR, see enum npu_sram_reg_idx */
#define PHX_SRAM_MBOX_CHANN_OFF_ADDR	MPNPU_SRAM_X2I_MAILBOX_0
#define PHX_SRAM_FW_ALIVE_OFF_ADDR	MPNPU_SRAM_I2X_MAILBOX_15

/* PCIe BAR Index for Phoenix Ryzen 7040 */
#define PHX_REG_BAR_INDEX  0
#define PHX_MBOX_BAR_INDEX 4
#define PHX_PSP_BAR_INDEX  0
#define PHX_SMU_BAR_INDEX  0
#define PHX_SRAM_BAR_INDEX 2
/* Associated BARs and Apertures */
#define PHX_REG_BAR_BASE  MPNPU_APERTURE0_BASE
#define PHX_MBOX_BAR_BASE MPNPU_APERTURE2_BASE
#define PHX_PSP_BAR_BASE  MPNPU_APERTURE0_BASE
#define PHX_SMU_BAR_BASE  MPNPU_APERTURE0_BASE
#define PHX_SRAM_BAR_BASE MPNPU_APERTURE1_BASE

#define FW_API_HASH_HIGH                0x025d29e860f79733
#define FW_API_HASH_LOW                 0xc8882da30379c869

const NPU_DEFINE_DEV_INFO(PHX, "RyzenAI-Phoenix", 1502, "amdnpu/1502/npu.sbin",
			  FW_API_HASH_HIGH, FW_API_HASH_LOW);
