#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Generate tools/WHENCE, the pinned firmware manifest snapshot used by release
# branches. main does not carry tools/WHENCE and always fetches the latest
# manifest live from the drm-firmware amd-ipu-staging branch.
#
# The snapshot records, for every device directory, the versioned real file and
# the stable "npu.dev.sbin" / "cert.dev.sbin" symlink that points at it, e.g.
#
#     File: amdnpu/17f1_10/1.8_npu.sbin.2.5.0.172
#     Link: amdnpu/17f1_10/npu.dev.sbin -> 1.8_npu.sbin.2.5.0.172
#
# Sources for the .dev.sbin -> versioned mapping, in order of preference:
#   1. The live amd-ipu-staging WHENCE, if it already carries the links.
#   2. tools/info.json firmwares[] (transition bootstrap for release lines that
#      predate the upstream links).

set -euo pipefail

FW_REPO="kernel-firmware/drm-firmware"
REF="amd-ipu-staging"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
INFO_JSON="${SCRIPT_DIR}/info.json"
OUT_WHENCE="${SCRIPT_DIR}/WHENCE"

usage()
{
  cat << USAGE_END
Usage: update_whence_snapshot.sh [-r <ref>] [-o <out>]
  -r <ref>   drm-firmware branch to snapshot (default: ${REF})
  -o <out>   output WHENCE path (default: ${OUT_WHENCE})
USAGE_END
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -r) REF="$2"; shift 2 ;;
    -o) OUT_WHENCE="$2"; shift 2 ;;
    -h|-help|--help) usage; exit 0 ;;
    *) echo "unknown option: $1"; usage; exit 1 ;;
  esac
done

echo "Resolving ${REF} on ${FW_REPO} ..."
COMMIT=$(git ls-remote "https://gitlab.com/${FW_REPO}.git" "${REF}" | awk 'NR==1{print $1}') || true
if [[ -z "${COMMIT}" ]]; then
  echo "error: could not resolve ${REF}" >&2
  exit 1
fi
echo "  ${REF} -> ${COMMIT}"

LIVE_WHENCE=$(curl -fsSL --max-time 60 "https://gitlab.com/${FW_REPO}/-/raw/${COMMIT}/WHENCE")

# Extract the amdxdna block from the live manifest.
AMDXDNA_BLOCK=$(awk '
  /^-----/ { if (in_section) exit; next }
  /^Driver:/ { in_section = ($0 ~ /^Driver: amdxdna/); next }
  in_section { print }
' <<< "${LIVE_WHENCE}")

# Collect File:/Link: entries. Prefer upstream links; otherwise bootstrap the
# mapping from info.json.
declare -a FILE_LINES LINK_LINES
UPSTREAM_LINKS=$(grep -E '^Link:.*\.dev\.sbin' <<< "${AMDXDNA_BLOCK}" || true)

if [[ -n "${UPSTREAM_LINKS}" ]]; then
  echo "Using .dev.sbin links from upstream WHENCE"
  mapfile -t FILE_LINES < <(grep -E '^File:' <<< "${AMDXDNA_BLOCK}")
  mapfile -t LINK_LINES < <(grep -E '^Link:' <<< "${AMDXDNA_BLOCK}")
else
  echo "Bootstrapping .dev.sbin links from ${INFO_JSON}"
  if [[ ! -f "${INFO_JSON}" ]] || [[ "$(jq '.firmwares | length' "${INFO_JSON}")" == "0" ]]; then
    echo "error: upstream WHENCE has no .dev.sbin links and info.json has no" >&2
    echo "       firmwares[] to bootstrap from." >&2
    exit 1
  fi
  declare -A SEEN_FILE
  while IFS= read -r entry; do
    dev_id=$(jq -r '.pci_device_id' <<< "${entry}")
    rev_id=$(jq -r '.pci_revision_id' <<< "${entry}")
    fw_name=$(jq -r '.fw_name' <<< "${entry}")
    version=$(jq -r '.version' <<< "${entry}")
    fw_type=${fw_name%%.*}   # npu.dev.sbin -> npu, cert.dev.sbin -> cert
    dir="${dev_id}_${rev_id}"
    ver_re=${version//./\\.}
    # Prefer the release-prefixed file that actually exists upstream for this
    # directory (e.g. 1.8_npu.sbin.2.5.0.172) so the installed symlink target
    # reveals the firmware release line and version. Fall back to the plain
    # name when no prefixed variant exists (e.g. npu1).
    target=$({ grep -E "^File: amdnpu/${dir}/[0-9]+\.[0-9]+_${fw_type}\.sbin\.${ver_re}$" <<< "${AMDXDNA_BLOCK}" || true; } \
             | head -n1 | sed -E "s|^File: amdnpu/${dir}/||")
    if [[ -z "${target}" ]]; then
      target="${fw_type}.sbin.${version}"
    fi
    file_path="amdnpu/${dir}/${target}"
    if [[ -z "${SEEN_FILE[${file_path}]:-}" ]]; then
      FILE_LINES+=("File: ${file_path}")
      SEEN_FILE[${file_path}]=1
    fi
    LINK_LINES+=("Link: amdnpu/${dir}/${fw_name} -> ${target}")
  done < <(jq -c '.firmwares[]' "${INFO_JSON}")
fi

echo "Writing ${OUT_WHENCE}"
{
  echo "# Generated by tools/update_whence_snapshot.sh - do not edit by hand."
  echo "# Pinned firmware manifest snapshot for this release branch."
  echo "# whence-ref: ${REF}"
  echo "# whence-commit: ${COMMIT}"
  echo ""
  echo "Driver: amdxdna - AMD Inference processor"
  echo ""
  printf '%s\n' "${FILE_LINES[@]}"
  printf '%s\n' "${LINK_LINES[@]}"
  echo ""
  echo "Licence: Redistributable. See LICENSE.amdnpu for details."
} > "${OUT_WHENCE}"

echo "Done. Snapshot pinned to ${REF}@${COMMIT}."
